---
- name: Include opensearch installation
  ansible.builtin.import_tasks: opensearch.yml

- name: Enable OpenSearch service
  ansible.builtin.systemd:
    name: opensearch
    enabled: true

- name: Start OpenSearch service
  ansible.builtin.systemd:
    name: opensearch
    state: started
  when: opencast_opensearch_started | bool
