---
- name: Include opensearch installation
  ansible.builtin.import_tasks: opensearch.yml

- name: Start and enable OpenSearch service
  ansible.builtin.systemd:
    name: opensearch
    enabled: true
    state: started

- name: Include reverse proxy configuration tasks
  ansible.builtin.include_tasks: nginx_reverse_proxy.yml
  when: >-
    opencast_opensearch_remote_user != None and
    opencast_opensearch_remote_password != None
